### PR TITLE
added distortion params for the depth camera

### PR DESCRIPTION
**Pull request by syedaraza**

### CODE REVIEW

**Comment by awesomebytes** [comment]
@syedaraza Did you test them? Could you attach a screenshot of the before and after this patch?
Probably with Rviz with the DepthCloud plugin showing a flat wall in front so the distortion can be appreciated. Just to double check the effect of it.

**Comment by syedaraza** [comment]
Yeah I tested those params. Changing them doesn't make any diffrerence.
withdistortionparams
withoutdistortionparams

**Comment by awesomebytes** [comment]
The difference maybe could be appreciated from the front?

Hmm, could you play with some values that are bigger and see if it does
anything?

If not, you could check the code of the plugin if those parameters are
actually being read and used... Maybe that should be the first step.

**Comment by syedaraza** [comment]
I analysed it from all the angles closely. But observed no visible difference.

The camera info topic shows the changed params for the distortion, D.

I am not sure from where the values of other params like P, R, and K are set. There is no option to set them in pepperGazebo.xacro

**Comment by awesomebytes** [comment]
When you say 'there is no option' you mean you don't see something
prefilled/commented with a 0?

All the parameters are optional so you need to find how they are named.
There is no instructions as far as I know.

I found this link that has more tags related to camera calibraron:

http://gazebosim.org/tutorials?tut=ros_depth_camera&cat=connect_ros

The plugin used is this one:
https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_plugins/include/gazebo_plugins/gazebo_ros_openni_kinect.h

You can check in the .cpp the parameters it's reading, but it seems to
inherit from a gazebo class...

The Gazebo part where this is implemented is in DepthCameraPlugin.hh/.cc :

https://github.com/arpg/Gazebo/tree/master/plugins

Dig a bit and find the parameters, if they are read at all (which I do
think they should as it works for RGB cameras). Its probably just a matter
of finding the correct tags for the .xacro file for that plugin.

**Comment by syedaraza** [comment]
Just added Cx, Cy and focalLength params which are used to compute the values for K, P, and R matrices. The values are computed in gazebo_ros_camera_utils.cpp

I played with the values by using randomly large values. The resulting clouds were wildly distorted, for example, like this,
largeparamvalues

**Comment by awesomebytes** [comment]
Cool! That makes more sense.

Do you appreciate any meaningful distortion with the actual values from the
robot?

**Comment by syedaraza** [comment]
Not really. Visibly the point cloud is the same.

The image with additional calibration params 
withmorecalibrationparams

Here is the camera info topic which shows the param values we obtained from the real Pepper.

header: 
  seq: 54
  stamp: 
    secs: 3
    nsecs: 929000000
  frame_id: "CameraDepth_optical_frame"
height: 240
width: 320
distortion_model: "plumb_bob"
D: [0.0015006388343578579, -0.0391088434247705, 0.002366597891470404, 0.004792417377891919, 0.0]
K: [283.79251147931114, 0.0, 166.86986665284704, 0.0, 283.79251147931114, 126.63268197434216, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [283.79251147931114, 0.0, 166.86986665284704, -0.0, 0.0, 283.79251147931114, 126.63268197434216, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False

**Comment by awesomebytes** [comment]
@syedaraza When you paste code (or code-like stuff, logs, or so) it's easier to read if you surround it by the code markup. In the Github interface the '**<>**' thing in the comment box, which is just surrounding the block with '```' (triple back-tick).

Hmm that's disappointing, that pointcloud does not look at all like a real one. Oh well, I guess it's better than nothing.

**Comment by syedaraza** [comment]
Ok cool!

**Pull request merged**
